### ISSUE TITLE
Wrong mail server

### ISSUE THREAD

**Issue by vladkras** [amaurymartiny/check-if-email-exists#1]
You have to find mail server first. You code doesn't work on most real domains. Try
`telnet gmail.com 587` It will hang forever. At least you have to nslookup mx server.

**Comment by amaurymartiny** [comment]
Yes correct, just tried gmail and it's hanging. As stated in the README, there's still some work to be done before it's usable by the public. If you want to make a PR i'll be delighted.

**Comment by vladkras** [comment]
I need this feature, but I'd better use golang for it
