### ISSUE TITLE
Create a SAAS out of this tool? 🤔

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/check-if-email-exists#155]
I've been tinkering about this idea:

There are tons of tools out there with the same goal ([xverify](https://www.xverify.com/), [EmailListVerify](https://www.emaillistverify.com/), [The Checker](https://thechecker.co/), [ZeroBounce](https://www.zerobounce.net/), etc...), but afaik they all somehow store the results in a DB.

I'm thinking of creating an email verification SAAS alternative, with **a tiny backend database<sup>1</sup>**, a focus on privacy, and open-source. It would be a paid service for larger volume, but there will always be a free tier - similar to what the forementioned services provide.

Put a thumbs up/down if you think this is a good idea or not.

Edit: Here's a start of the SAAS: https://reacherhq.github.io

<sup>1: The backend will store the user accounts, manage payments, keep track of their remaining "credits" to verify more emails... But it will never store the actual emails or their deliverability results.</sup>

**Comment by taewookim** [comment]
Keep getting

{
  "error": "TypeError: Failed to fetch"
}


on any email addresses

**Comment by taewookim** [comment]
I'd be willing to give it a shot if you can make it cost effective and accurate (i mean less than <.1% error rate). I hate managing servers / network operations. Would rather focus on product development.

**Comment by markronquillo** [comment]
Same here, keep getting failed to fetch error.

**Comment by amaurymartiny** [comment]
@taewookim @markronquillo sorry about that, should be fixed now

**Comment by amaurymartiny** [comment]
It's done: https://reacher.email ✅
