### ISSUE TITLE
Make it faster!

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/check-if-email-exists#19]
Right now, to check a Gmail address, it take 10-15 seconds to resolve. It would be really good to make it faster.

If anyone stumbles upon on this issue and has some ideas/heuristics, I'm interested.

**Comment by mailme-gx** [comment]
> Right now, to check a Gmail address, it take 10-15 seconds to resolve. It would be really good to make it faster.
> 
> If anyone stumbles upon on this issue and has some ideas/heuristics, I'm interested.

all tests I tried for gmail took ~700 milliseconds regardless if checking one or ten addresses per request

can you please provide more information
