### ISSUE TITLE
Add docker image

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/check-if-email-exists#21]

**Comment by shinebayar-g** [comment]
How would you like to build docker image? I guess if it's not web service, docker image wouldn't have that much usefulness here?

**Comment by amaurymartiny** [comment]
> I guess unless you build web service

Yes, that's what I had in mind, a small http service like you described in #46

**Comment by shinebayar-g** [comment]
Nice! That would be really useful. Thank you.

**Comment by amaurymartiny** [comment]
Fixed by #86.

Released at https://hub.docker.com/r/amaurymartiny/check-if-email-exists.
