### ISSUE TITLE
:latest docker image doesn't work

### ISSUE THREAD

**Issue by lukaville** [amaurymartiny/check-if-email-exists#235]
When running the latest image it doesn't work:

```
docker run -p 3000:3000 amaurymartiny/check-if-email-exists
```

```
➜  ~ curl -X POST -d'{"from_email":"user@example.org","to_email":"someone@gmail.com"}' http://localhost:3000
curl: (52) Empty reply from server
```

Looks like it's because the server listens on 127.0.0.1. The image with tag `v0.6.6` works perfectly.

**Comment by amaurymartiny** [comment]
Yes, you're right. I justed updated the latest tag so that it contains the same image as 0.6.6.

**Comment by september-evgeny** [comment]
> Yes, you're right. I justed updated the latest tag so that it contains the same image as 0.6.6.

can't work docker latest image:
curl -X POST -d'{"to_email":"someone@gmail.com"}' http://localhost:3005
curl: (52) Empty reply from server
