### ISSUE TITLE
Fail to check work related emails

### ISSUE THREAD

**Issue by markronquillo** [amaurymartiny/check-if-email-exists#275]
Hello,

I tried to use the tool and check work related emails like {name}@thoughtworks.com, {name}@guidebook.com but it returns this error

```
450, "4.2.1",  The user you are trying to contact is receiving mail at a rate that prevents additional messages from being delivered. Please resend your message at a later time. If the user is able to receive mail at that time, your message will be delivered. 
```

I tried it on 2-3 more company emails but the result is the same. Does this mean that the tool doesn't work on company/work emails?

Thanks

**Comment by amaurymartiny** [comment]
I just checked 2 emails both thoughtworks.com and guidebook.com, and they work (it shows is_deliverable=true). Could you send me an email (my email is in the core/Cargo.toml file) with some non-working email addresses.

**Comment by markronquillo** [comment]
thank you! email sent.
