### ISSUE TITLE
Add HTTP server to cli

### ISSUE THREAD

**Issue by shinebayar-g** [amaurymartiny/check-if-email-exists#46]
Currently [online version](https://github.com/amaurymartiny/check_if_email_exists/issues/9) returns more information than binary version. It would be nice to have those additional information in binary version.

Actually would you make it http server? So users could deploy it and use as backend service. It would be super nice.

**Comment by amaurymartiny** [comment]
The JSON output from the binary has been added in [v0.3.1](https://github.com/amaurymartiny/check_if_email_exists/releases/tag/v0.3.1) 🚀 .

I'm working on the HTTP server now

**Comment by amaurymartiny** [comment]
Fixed by #85. Released in [`v0.6.0`](https://github.com/amaurymartiny/check-if-email-exists/releases/tag/v0.6.0) 🚀.
