### ISSUE TITLE
Compile error "reached the type-length limit while instantiating"

### ISSUE THREAD

**Issue by blkhlouf1** [amaurymartiny/check-if-email-exists#568]
Issue found on deploy with Heroku : 

Compiling check-if-email-exists-cli v0.8.13 (/tmp/build_092091e8_)
error: reached the type-length limit while instantiating `<std::iter::Map<std::iter::Map<s..., ()}]>, ()}]>}]>}]>>::Future}]>`
    |
    = note: consider adding a `#![type_length_limit="2016981"]` attribute to your crate
error: aborting due to previous error
error: could not compile `check-if-email-exists-cli`.

**Comment by amaurymartiny** [comment]
I added the following lines, as per the hint (with a much larger number):

https://github.com/amaurymartiny/check-if-email-exists/blob/889e52170ef44aa92cfd8e74b177a41f838b841b/src/main.rs#L17-L18

I'm leaving this issue open, if anyone has ideas.

**Comment by mre** [comment]
@amaurymartiny seems like it's an issue with the Rust 1.46 toolchain.
Using a newer version (1.47+) seems to fix it.
See rust-lang/rust#54540 and https://github.com/hello-rust/lychee/pull/9 for a fix.
Credits go to @xiaochuanyu and @pawroman.

**Comment by amaurymartiny** [comment]
fixed in #665

**Comment by Guardian-Spirit** [comment]
Yeah, it compiles now, but... it takes eternity to compile.

Cold build of my project without use of check_if_emails_exists takes 1 minute, whereas build with use of it takes... 9 minutes 50 seconds.
