### ISSUE TITLE
Catch All parse failed

### ISSUE THREAD

**Issue by marcelinhov2** [amaurymartiny/check-if-email-exists#569]
Hey, I'm getting an error that I think could be avoided.

For outlook server sometimes I get this return:
![image](https://user-images.githubusercontent.com/232648/91592821-81e49080-e935-11ea-93c5-7e80402c8cab.png)

If I'm not wrong, this is a catch all return, am I right?

Thanks.

**Comment by amaurymartiny** [comment]
Hmm, looking at https://answers.microsoft.com/en-us/outlook_com/forum/all/server-error-452-453-error-too-many-recipients/6e741eef-c85e-4fb6-981d-cf6a65c755ab, it seems it's just a rate-limiting error. What do you think?

**Comment by slimakcz** [comment]
I have the same issue. When I trying check_if_email_exists the result is "transient: 4.5.3 Too many recipients (AS780090) [SN1NAM02FT003.eop-nam02.prod.protection.outlook.com]", but manual check from the same server is ok.
![obrazek](https://user-images.githubusercontent.com/19480248/98803675-6b6ab300-2415-11eb-93a2-8032c34e505f.png)

**Comment by amaurymartiny** [comment]
@slimakcz Interesting, could you run the same command with `RUST_LOG=debug check_if_email_exists ...`. This will show the intermediate SMTP commands `check_if_email_exists` is using, and we can compare to the telnet ones.

**Comment by slimakcz** [comment]
@amaurymartiny 
[2020-11-11T11:35:24Z DEBUG async_smtp::smtp::client::inner] >> MAIL FROM:<slimak@seznam.cz><CRLF>
[2020-11-11T11:35:24Z DEBUG async_smtp::smtp::client::inner] << 250 2.1.0 Sender OK<CRLF>
[2020-11-11T11:35:24Z DEBUG async_smtp::smtp::client::inner] >> RCPT TO:<z88EvVgn94m8Hcl@fasm.edu.br><CRLF>
[2020-11-11T11:35:24Z DEBUG async_smtp::smtp::client::inner] << 250 2.1.5 Recipient OK<CRLF>
[2020-11-11T11:35:24Z DEBUG async_smtp::smtp::client::inner] >> RCPT TO:<asilva@fasm.edu.br><CRLF>
[2020-11-11T11:35:25Z DEBUG async_smtp::smtp::client::inner] << 452 4.5.3 Too many recipients (AS780090) [CY1NAM02FT054.eop-nam02.prod.protection.outlook.com]<CRLF>

the "RCPT TO:<z88EvVgn94m8Hcl@fasm.edu.br>" looks strange

**Comment by amaurymartiny** [comment]
AH. the z88 one is to check for catch-all: we generate a random username, and test `{username}@{domain}`. Is it's 250, then the provider is catch-all.

I think the best would be to do:
- if it's catch-all, then we skip checking the inputted email
- if it's not catch-all, then we check the inputted email.

https://github.com/amaurymartiny/check-if-email-exists/blob/18a97afa08c32ca72fa9ac6476bbc93618558b5e/core/src/smtp/mod.rs#L357-L360

@slimakcz Would you like to create a PR?

**Comment by slimakcz** [comment]
@amaurymartiny thank you so much for very fast answer.
I can't program in RUST, so I need to find some colleagues to help me :-)
And I find another false negative result:
![obrazek](https://user-images.githubusercontent.com/19480248/98810345-64e13900-241f-11eb-9ede-c570f6a1bfbc.png)
Maybe will be better if catch-all is negative to open new connection just with inputted email and create switch if user wan't to try catch_all (for save new connections).
I must more thinking about it, I am not sure if this solutions is best, maybe have some consequences and also I don't know if is this solution good for you.

**Comment by amaurymartiny** [comment]
@slimakcz I just released 0.8.15, which I think should solve both issues, can you confirm?

**Comment by slimakcz** [comment]
@amaurymartiny yes, both issue was solved. thank you so much
