### ISSUE TITLE
This email verification tool actually connects to the mail server and checks whether the mailbox exists or not

### ISSUE THREAD

**Issue by abdidarmawan007** [amaurymartiny/check-if-email-exists#580]
This email verification tool actually connects to the mail server
and checks whether the mailbox exists or not ?

for example i have email address not exist escada_gustaman@yahoo.com, this software or product can check email address exist or not ?

**Comment by abdidarmawan007** [comment]
i try to test you software and product can't check mailbox exists or not

curl -X POST -d'{"to_emails":["escada_gustaman@yahoo.com"]}' http://localhost:3000
[{"input":"escada_gustaman@yahoo.com","is_reachable":"safe","misc":{"is_disposable":false,"is_role_account":false},"mx":{"accepts_mail":true,"records":["mta5.am0.yahoodns.net.","mta6.am0.yahoodns.net.","mta7.am0.yahoodns.net."]},"smtp":{"can_connect_smtp":true,"has_full_inbox":false,"is_catch_all":false,"is_deliverable":true,"is_disabled":false},"syntax":{"address":"escada_gustaman@yahoo.com","domain":"yahoo.com","is_valid_syntax":true,"username":"escada_gustaman"}}]

![alt text](https://i.imgur.com/rxJ9CeB.png)

**Comment by amaurymartiny** [comment]
Yes, this tool checks whether an email exists or not. `safe` means it exists, see [the FAQ](https://www.notion.so/reacherhq/Reacher-FAQ-389d6f51a53749f29d914239613c64eb) for more info.

For yahoo addresses, it's a bit hard to test their deliverability. `safe` means "it exists", but might be disabled (see #473)

**Comment by abdidarmawan007** [comment]
@amaurymartiny its clear now, thanks
