### ISSUE TITLE
Pass proxy details via POST request

### ISSUE THREAD

**Issue by therightprofile** [amaurymartiny/check-if-email-exists#589]
First of all, thanks for developing this, it's been really helpful for us.

Is it possible to pass the proxy-host and proxy-port via POST request along with the to_emails parameter? 

Thanks!

**Comment by amaurymartiny** [comment]
Thanks! Yes, that's possible. Would you be willing to make a PR?

**Comment by therightprofile** [comment]
Here you go #590 

First time coding in Rust but this seems to be working as intended

**Comment by roshanjonah** [comment]
I got a slightly different question that is still related to this - How can I specify SOCKS5 password? @amaurymartiny 

Also, is there a way to use 587 or other mailing ports to verify email as opposed to just 25? Because 25 is blocked :(

**Comment by amaurymartiny** [comment]
@roshanjonah  Could you create separate issues for those?
