### ISSUE TITLE
Locaweb closing smtp connection

### ISSUE THREAD

**Issue by tmazawi** [amaurymartiny/check-if-email-exists#746]
Hey
what an awsome project, thanks for sharing.
just noticed that any email hosted at Locaweb can't be verifed because the server closes the connection
which make the verification status to unknown
here is one example of an email hosted at locaweb for test
marcelo@aliancamultiservice.com.br

Thanks

**Comment by amaurymartiny** [comment]
https://github.com/amaurymartiny/check-if-email-exists#what-does-is_reachable-unknown-mean

Have a look at your SMTP port 25.

**Comment by tmazawi** [comment]
You're right it's working for reacher.email
strange i'm using heroku free account with the link you provided to deploy
are the heroku and reacher.email identical ?

**Comment by amaurymartiny** [comment]
Reacher uses multiple heroku instances (and other providers too, for better results).

I think this issue is related to providers and infrastructure, are you okay to close the issue?

**Comment by tmazawi** [comment]
sure thanks for the feedback
