### ISSUE TITLE
Is the binary less accurate than running on server (via docker)? 

### ISSUE THREAD

**Issue by taewookim** [amaurymartiny/check-if-email-exists#757]
Repo readme comment:

> Note: The binary doesn't connect to any backend, it checks the email directly from your computer.

Is the docker version running on server with open SMTP port more accurate?

Are there best practices on how to make the responses more accurate? Some ideas I had (not sure if these are worth doing)

- set the "FROM" email / domain with MX record pointing to the IP where the docker is running
- checking against spamhaus / RBL to see if IP or from email you're using is blacklisted
- round-robbin SMTP servers if doing bulk check (like variations f.last@domain.com, flast@domain.com ,firstlast@domain.com, etc)

**Comment by amaurymartiny** [comment]
It's the same accuracy, because Docker just runs the binary. Your 3 suggestions are totally valid, however, I see only the (2) can be applied to this repository. The (1) and (3) are infrastructure related.

I run https://reacher.email, happy to discuss with you if you have ideas with low-end VPS. Can you send me an email at amaury@reacher.email?

**Comment by taewookim** [comment]
> It's the same accuracy, because Docker just runs the binary. 

I see. So the results are same for open or closed port (port 25)?

Maybe I misunderstood the SMTP protocol but i thought the smtp server you're querying sends something back via port 25.

**Comment by amaurymartiny** [comment]
I'm not sure I understand the question.

it's either:

`docker --(port 25)--> email's SMTP server --(port 25)--> docker`
or 
`binary --(port 25)--> email's SMTP server --(port 25)--> binary`

In both cases, port 25 needs to be open. Behind the scenes, the dockerfile just runs the binary:
https://github.com/amaurymartiny/check-if-email-exists/blob/94d703053387cdf6a7275d26e8fd7a43e9deaf3b/Dockerfile#L17

**Comment by taewookim** [comment]
AH gotcha
I re-read the README.. clear now. Thanks @amaurymartiny

**Comment by taewookim** [comment]
BTW.. is there a feature in progress to see if the IP hosting check-if-email-exists has been blacklisted? would be nice if it can self-diagnose every X days and send email to admin if that's case.

**Comment by amaurymartiny** [comment]
> BTW.. is there a feature in progress to see if the IP hosting check-if-email-exists has been blacklisted? would be nice if it can self-diagnose every X days and send email to admin if that's case.

Yeah, that's a good idea. Would you like to create an issue for that?

**Comment by taewookim** [comment]
will do
