### ISSUE TITLE
Does 0.8.17 have a linux build binary?

### ISSUE THREAD

**Issue by taewookim** [amaurymartiny/check-if-email-exists#821]

**Comment by tyranron** [comment]
I guess it's because of <https://travis-ci.org> is shutting down, so [the pipeline](https://github.com/amaurymartiny/check-if-email-exists/blob/v0.8.17/.travis.yml) haven't even run.

The migration to <https://travis-ci.com> should be performed, or event better to GitHub Actions altogether.

**Comment by amaurymartiny** [comment]
Hmm, it seems that the pipelines did run: https://travis-ci.org/github/amaurymartiny/check-if-email-exists/builds/753009973.

Also weird that the macos binary is correctly uploaded.

I just restarted the 2 linux jobs, let's see what happens.

**Comment by amaurymartiny** [comment]
Oh well, re-ran the job and the binaries are there.
